---
title: "Assignment 8"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(flexdashboard)
library(tidyverse)
library(shiny)
library(ggplot2)
library(ggiraph)


tornados <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-16/tornados.csv')
```
Column {.sidebar}
-----------------------------------------------------------------------
```{r}
dateRangeInput("date_range", "Select Date Range",
               start = "1950-01-01", end = "2023-12-31",
               format = "yyyy-mm-dd",
               startview = "decade")

```

Column {data-width="450"}
-----------------------------------------------------------------------
```{r}
injuries <- tornados %>%
  group_by(yr) %>%
  summarize(injuries = mean(inj))

output$interactive_plot <- renderGirafe({
  gg <- ggplot(injuries, aes(x = yr, y = injuries)) +
    geom_line() +
    geom_point_interactive(aes(tooltip = paste("Year:", yr, "<br> Injuries per Tornado:", sprintf("%.2f", injuries))), size = 1) +
    geom_smooth(method = "lm", se = FALSE) +
    labs(title = "Injuries Per Tornado", x = "Year")

  ggiraph(ggobj = gg) 
})

girafeOutput("interactive_plot")
```

Column {data-width="450"}
-----------------------------------------------------------------------
```{r}
output$bar_plot <- renderPlot({
  filtered_data <- tornados %>%
    filter(between(as.Date(date), input$date_range[1], input$date_range[2]))
  
  top10 <- filtered_data %>%
    arrange(desc(len)) %>%
    slice_head(n = 10)
  
  ggplot(top10, aes(x = reorder(om, -len), y = len)) +
    geom_bar(stat = "identity", fill = "skyblue") +
    labs(x = "Tornado Number", y = "Length", title = "Top 10 Tornado Lengths") +
    theme_minimal() +
    coord_flip()
})
plotOutput("bar_plot")


```

